/** `soku changelog` — what changed between two CLI versions.
 *
 * Upgrading used to invalidate whatever an agent believed about the CLI's
 * surface with no way to find out what actually moved: the capability count
 * jumped, the runtime help was current, and nothing connected the two. This
 * reads a changelog bundled with the installed CLI, so the answer needs no
 * network call and always describes the binary that is running.
 *
 * The capability sections are generated by `scripts/capability-diff.mjs` from
 * two capability manifests; the command and note sections are written by hand,
 * because the manifest only covers data actions and says nothing about
 * sub-commands like `automation` or `context`.
 */

import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

import { Command } from 'commander'

import { bold, cyan, dim, emitError, emitSuccess, ExitCode, table } from '../output/envelope.js'
import { compareSemverish } from '../update-check.js'
import { CLI_VERSION } from '../version.js'

/** Version label for changes merged but not yet published to npm. */
export const UNRELEASED = 'unreleased'

export interface CapabilityChange {
  id: string
  fields: string[]
}

export interface CapabilityRef {
  id: string
  mode: string | null
  description: string | null
}

export interface CapabilityDiff {
  counts: {
    before: number
    after: number
    added: number
    removed: number
    changed: number
  }
  added: CapabilityRef[]
  removed: CapabilityRef[]
  changed: CapabilityChange[]
  /** Set on an entry that has no predecessor to diff against. */
  baseline?: boolean
}

export interface CommandDiff {
  added: string[]
  changed: string[]
  removed: string[]
}

export interface ChangelogEntry {
  version: string
  date: string | null
  notes: string[]
  commands: CommandDiff
  capabilities: CapabilityDiff
}

export interface Changelog {
  schemaVersion: number
  /** Earliest version this file can speak for. */
  historyStartsAt: string
  entries: ChangelogEntry[]
}

/** Load the changelog shipped alongside the compiled CLI. */
export function loadChangelog(): Changelog {
  const path = fileURLToPath(new URL('../generated/changelog.json', import.meta.url))
  return JSON.parse(readFileSync(path, 'utf8')) as Changelog
}

/** Entries newer than `since`, newest first.
 *
 * `unreleased` always sorts newest — it is, by definition, ahead of every
 * published version. A `since` the file cannot speak for is the caller's
 * problem to know about, so `selectEntries` reports it rather than quietly
 * returning everything it happens to hold.
 */
export function selectEntries(
  changelog: Changelog,
  since?: string,
): { entries: ChangelogEntry[]; truncated: boolean } {
  if (!since) return { entries: changelog.entries, truncated: false }
  const entries = changelog.entries.filter(
    (entry) => entry.version === UNRELEASED || compareSemverish(entry.version, since) > 0,
  )
  const truncated = compareSemverish(since, changelog.historyStartsAt) < 0
  return { entries, truncated }
}

function renderEntry(entry: ChangelogEntry): string {
  const heading = `${bold(cyan(entry.version))}${entry.date ? dim(`  ${entry.date}`) : ''}`
  const lines = [heading]

  for (const note of entry.notes) lines.push(`  ${note}`)

  const commandLines: string[] = []
  for (const [label, names] of [
    ['added', entry.commands.added],
    ['changed', entry.commands.changed],
    ['removed', entry.commands.removed],
  ] as const) {
    if (names.length > 0) commandLines.push(`  commands ${label}: ${names.join(', ')}`)
  }
  lines.push(...commandLines)

  const caps = entry.capabilities
  if (caps.baseline) {
    lines.push(`  capabilities: ${caps.counts.after} (baseline)`)
  } else {
    lines.push(
      `  capabilities: ${caps.counts.before} → ${caps.counts.after}` +
        ` (${caps.counts.added} added, ${caps.counts.removed} removed, ${caps.counts.changed} changed)`,
    )
    if (caps.added.length > 0) {
      lines.push(dim('  added:'))
      lines.push(
        table(
          caps.added.map((item) => ({ id: item.id, mode: item.mode ?? '', description: item.description ?? '' })),
          [
            { key: 'id', header: '  ACTION' },
            { key: 'mode', header: 'MODE' },
            { key: 'description', header: 'DESCRIPTION' },
          ],
        ),
      )
    }
    if (caps.removed.length > 0) {
      lines.push(dim('  removed:'))
      for (const item of caps.removed) lines.push(`    ${item.id}`)
    }
    if (caps.changed.length > 0) {
      lines.push(dim('  changed:'))
      for (const item of caps.changed) lines.push(`    ${item.id} (${item.fields.join(', ')})`)
    }
  }
  return lines.join('\n')
}

export function renderChangelog(data: {
  cliVersion: string
  since: string | null
  truncated: boolean
  historyStartsAt: string
  entries: ChangelogEntry[]
}): string {
  if (data.entries.length === 0) {
    return dim(`No recorded changes after ${data.since ?? data.cliVersion}.`)
  }
  const parts = data.entries.map(renderEntry)
  if (data.truncated) {
    parts.push(
      dim(
        `Note: this changelog starts at ${data.historyStartsAt}; changes before that version are not recorded here.`,
      ),
    )
  }
  return parts.join('\n\n')
}

export function registerChangelogCommand(program: Command): void {
  program
    .command('changelog')
    .description('Show what changed in this CLI: commands and capabilities, per version')
    .option(
      '--since <version>',
      'Only versions newer than this one (e.g. the version you upgraded from)',
    )
    .option('--summary', 'Counts only — omit the per-action lists')
    .action((opts: { since?: string; summary?: boolean }) => {
      let changelog: Changelog
      try {
        changelog = loadChangelog()
      } catch (err) {
        emitError(
          'changelog_unavailable',
          `Could not read the bundled changelog: ${(err as Error).message}`,
          ExitCode.RUNTIME,
        )
      }
      const { entries, truncated } = selectEntries(changelog, opts.since)
      const shaped = opts.summary
        ? entries.map((entry) => ({
            ...entry,
            capabilities: { ...entry.capabilities, added: [], removed: [], changed: [] },
          }))
        : entries
      emitSuccess(
        {
          cliVersion: CLI_VERSION,
          since: opts.since ?? null,
          truncated,
          historyStartsAt: changelog.historyStartsAt,
          entries: shaped,
        },
        renderChangelog,
      )
    })
}
